---
- name: Install and configure httpd
  hosts: nodes
  become: yes
  tasks:
    - name: Install httpd & firewalld
      yum:
        name:
          - "{{ web_package }}"
          - "{{ firewall_package }}"
        state: latest
    - name: Enable and Start httpd
      service:
        name: "{{ web_package }}"
        enabled: true
        state: started
    - name: Enable and Start firewalld
      service:
        name: firewalld
        enabled: true
        state: started
    - name: Open firewall  ports
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
    - name: Copy html content
      copy:
        content: "Welcome to our websirte"
        dest: /var/www/html/index.html


- name: Test and verify webservers
  hosts: localhost
  become: no
  tasks:
    - name: connect to the wenserver
      uri: 
        url: http://node1
        status_code: 200
